version '1'
services:
  app:
    build: .
  environment:
    - BUILDKITE
    - BUILDKITE_API_TOKEN
    - BUILDKITE_BRANCH
    - BUILDKITE_BUILD_NUMBER
    - BUILDKITE_BUILD_URL
    - BUILDKITE_COMMIT
    - BUILDKITE_PROJECT_SLUG
    - BUILDKITE_PULL_REQUEST
    - BUILDKITE_REPO
    - CI
    - CODECOV_TOKEN
    - DANGER_GITHUB_API_TOKEN
