version: '2'
services:
  library:
    build: .
    tmpfs: /tmp
    # volumes:
    #   - "./build:/app/lib/build"
    environment:
      - BUILDKITE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_API_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PARALLEL_JOB_COUNT
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - CI
      - NPM_AUTH_TOKEN
      - CODECOV_TOKEN
      - DANGER_GITHUB_API_TOKEN
