steps:
  - name: ":docker:"
    plugins:
      docker-compose:
        build: app
        image-repository: #path-to-server
    agents:
      queue: elastic-builders
  - wait
  - name: ":build:"
    command: yarn build
    artifact_paths: 'dist/stats.json'
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
  - wait
  - name: ":eslint:"
    command: yarn lint:js
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
  - name: ":stylelint:"
    command: yarn lint:css
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
  - name: ":jest:"
    command: yarn test --coverage
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
    env:
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PROJECT_SLUG
      - CODECOV_TOKEN
  - name: ":danger:"
    command: yarn danger ci
    timeout_in_minutes: 10
    env:
      - BUILDKITE
      - BUILDKITE_API_TOKEN
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - CI
      - DANGER_GITHUB_API_TOKEN
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
