steps:
  - name: ":docker:"
    plugins:
      docker-compose#v2.4.1:
        build: library
        # image-repository: #path-to-server
    # agents:
    #   queue: elastic-builders
    # timeout_in_minutes: 10

  - wait

  - name: ":hammer_and_wrench:"
    command: yarn build
    # https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#artifacts
    # artifact_paths: 'lib/*'
    # artifact_paths: 'dist/stats.json'
    timeout_in_minutes: 10
    # agents:
    #   queue: elastic
    plugins:
      docker-compose#v2.4.1:
        run: library
    env:
      - NPM_AUTH_TOKEN

  - wait

  - name: ":eslint:"
    command: yarn lint:js
    timeout_in_minutes: 2
  #   agents:
  #     queue: elastic
    plugins:
      docker-compose#v2.4.1:
        run: library

  - name: ":stylelint:"
    command: yarn lint:css
    timeout_in_minutes: 2
  #   agents:
  #     queue: elastic
    plugins:
      docker-compose#v2.4.1:
        run: library

  - name: ":jest:"
    command: ./.buildkite/steps/test.sh
    timeout_in_minutes: 10
    # agents:
    #   queue: elastic
    plugins:
      docker-compose#v2.4.1:
        run: library
    env:
      - CODECOV_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PROJECT_SLUG

  # - name: ":danger:"
  #   command: yarn danger ci
  #   timeout_in_minutes: 10
  #   env:
  #     - BUILDKITE
  #     - BUILDKITE_API_TOKEN
  #     - BUILDKITE_PULL_REQUEST
  #     - BUILDKITE_REPO
  #     - CI
  #     - DANGER_GITHUB_API_TOKEN
  #   agents:
  #     queue: elastic
  #   plugins:
  #     docker-compose#v2.4.1:
  #       run: app

